### ISSUE TITLE
Bump React dependency?

### ISSUE THREAD

**Issue by markerikson** [ashr81/react-tiny-toast#5]
Looking at the lib and it seems very nicely done. But, there doesn't seem to be any reason to limit the React peer dependency to `">=17.0.0 <18.0"` - it looks like its should work with any React version greater than 16.8 (when hooks were introduced).  This leads to peer dep warnings with React 18.

Could you update the peer dep here?

**Comment by ashr81** [comment]
@markerikson That's a fair point. I allowed the package to accept all the versions equal to and above `16.8`.

I released a new version with the changes you asked for here: https://www.npmjs.com/package/react-tiny-toast (version: 2.1.0). Please let me know if this addresses the current issue. 😃

**Comment by markerikson** [comment]
Thanks!
